### ISSUE TITLE
Icon needs to be changed

### ISSUE THREAD

**Issue by andreimpircalaboiu** [andreimpircalaboiu/around#1]
We need to propose some variants of a new icon for the game. And then choose one of them

**Comment by andreimpircalaboiu** [comment]
We had to choose between these two: 
![aroundicon1bluegreen](https://cloud.githubusercontent.com/assets/11775114/19085734/0fb6abd4-8a74-11e6-9c69-7177441ebac1.png) 
and 
![14569710_1170255686378845_1831294227_n](https://cloud.githubusercontent.com/assets/11775114/19085741/17e8a49c-8a74-11e6-9acd-e2b3d6d7cc03.png) .

We will go with the second one for the first release.

**Comment by BogdanH95** [comment]
We updated the icon:
![icon4](https://cloud.githubusercontent.com/assets/22543918/19087085/6b7f603c-8a79-11e6-910b-1636871b19cf.png)

**Comment by andreimpircalaboiu** [comment]
Fixed and closed. 5532c719e79afc3256b1f31fcff6aaf4d5684cd9

**Comment by andreimpircalaboiu** [comment]
The new icon need to be allocated as sprite.
